#ifndef ALL_H
#define ALL_H

#include "animal.h"
#include "cage.h"
#include "cell.h"
#include "zoo.h"
#include "driver.h"

#include "CellType/air_habitat.h"
#include "CellType/land_habitat.h"
#include "CellType/park.h"
#include "CellType/restaurant.h"
#include "CellType/road.h"
#include "CellType/water_habitat.h"

#include "AnimalType/amphibia.h"
#include "AnimalType/aves.h"
#include "AnimalType/flying_animal.h"
#include "AnimalType/land_animal.h"
#include "AnimalType/mamalia.h"
#include "AnimalType/pisces.h"
#include "AnimalType/reptil.h"
#include "AnimalType/water_animal.h"

#include "AnimalType/Species/bunglon.h"
#include "AnimalType/Species/burung_unta.h"
#include "AnimalType/Species/cendrawasi.h"
#include "AnimalType/Species/elang.h"
#include "AnimalType/Species/flamingo.h"
#include "AnimalType/Species/gajah.h"
#include "AnimalType/Species/goliath_frog.h"
#include "AnimalType/Species/gorila.h"
#include "AnimalType/Species/harimau.h"
#include "AnimalType/Species/komodo.h"
#include "AnimalType/Species/kucing.h"
#include "AnimalType/Species/lumba_lumba.h"
#include "AnimalType/Species/merak.h"
#include "AnimalType/Species/monyet.h"
#include "AnimalType/Species/orangutan.h"
#include "AnimalType/Species/panda.h"
#include "AnimalType/Species/pari.h"
#include "AnimalType/Species/paus_humpback.h"
#include "AnimalType/Species/pinguin.h"
#include "AnimalType/Species/puma.h"
#include "AnimalType/Species/salmon.h"
#include "AnimalType/Species/salamander.h"
#include "AnimalType/Species/simpanze.h"
#include "AnimalType/Species/singa.h"

#endif
